version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: laravel_prod_app
    expose:
      - "9000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx.prod
    container_name: laravel_prod_nginx
    ports:
      - "80:80"
    depends_on:
      - app

