# Dockerfile.nginx.prod
FROM nginx:stable-alpine

# Copiar el archivo de configuración
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

# Copiar solo la carpeta public desde el build Laravel
COPY ./public /var/www/public
