  services:
    # Servicio de la aplicación Laravel (PHP-FPM)
    app:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: laravel_app
      working_dir: /var/www
      restart: unless-stopped
      volumes:
        - .:/var/www
      ports:
        - "9000"
      command: >
        sh -c "chown -R www-data:www-data storage bootstrap/cache &&
              chmod -R 775 storage bootstrap/cache &&
              php-fpm"
      networks:
        - app-network

    nginx:
      image: nginx:stable-alpine
      container_name: laravel_nginx
      restart: unless-stopped
      ports:
        - "80:80"
      volumes:
        - .:/var/www
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - app
      networks:
        - app-network
    redis:
      image: redis:alpine
      container_name: laravel_redis
      ports:
        - "6379:6379"
      restart: always
      networks:
        - app-network
    
    horizon_worker:
      build:
        context: .
        dockerfile: Dockerfile
      image: laravel_app
      container_name: laravel_horizon_worker
      depends_on:
        - redis
        - app
      restart: unless-stopped
      working_dir: /var/www
      command: php artisan horizon
      volumes:
        - ./:/var/www
      networks:
        - app-network
    mailhog:
      image: mailhog/mailhog
      container_name: laravel_mailhog
      ports:
        - "1025:1025"  # SMTP
        - "8025:8025"  # Web UI
      networks:
        - app-network
  networks:
    app-network:
      driver: bridge